chore: integrate map libre
digidem/comapeo-desktop pull request #61
Opened 2024-12-13 21:35 UTC by cimigree

closes #43 
- Adds the basic map libre map. I imagine there are specifications somewhere about which map package styler we want to use, but at this juncture, I am not sure what they are. This is just a cartoon globe at this point.
- Adds a location context. I am not sure if this is necessary as I imagine coordinates will come from observations but I am adding it for now
- If we want to use the built in geolocation in production, it looks like we need a Google Cloud Api key, which is why I provided an alternative to try

> GOOGLE_API_KEY
> Geolocation support in Electron requires the use of Google Cloud Platform's geolocation webservice. To enable this feature, acquire a [Google API key](https://developers.google.com/maps/documentation/geolocation/get-api-key) and place the following code in your main process file, before opening any browser windows that will make geolocation requests:
> 
> process.env.GOOGLE_API_KEY = 'YOUR_KEY_HERE'
> 
> By default, a newly generated Google API key may not be allowed to make geolocation requests. To enable the geolocation webservice for your project, enable it through the [API library](https://console.cloud.google.com/apis/library).
> 
> N.B. You will need to add a [Billing Account](https://cloud.google.com/billing/docs/how-to/payment-methods#add_a_payment_method) to the project associated to the API key for the geolocation webservice to work.

2025-01-06 18:56 UTC, achou11 requested changes

2025-01-06 18:56 UTC, achou11 commented on package.json
> +		"maplibre-gl": "^4.7.1",
although very new, will highlight that v5 was released last week

https://github.com/maplibre/maplibre-gl-js/releases/tag/v5.0.0

although I guess if we use a react wrapper, that should dictate the version we use. most likely v4 for now but if it supports v5, great!

2025-01-06 18:56 UTC, achou11 commented on src/renderer/src/components/Map.tsx
think it would be worth using a [React wrapper](https://maplibre.org/maplibre-gl-js/docs/plugins/#react) for this given our eventual needs.

https://visgl.github.io/react-maplibre/ seems to be the option I'd lean towards right now

2025-01-06 18:56 UTC, achou11 commented on src/renderer/src/contexts/SharedLocationContext.tsx
Have we gotten an answer to the question about needing geolocation support in desktop? If there's not an immediate need for it, I would suggest omitting it entirely and have this PR focus on rendering the map with a hardcoded center or (eventually) based on the observation data.

Especially with the caveat you mention about the API key and all, I think introducing is more work than necessary right now.

2025-01-06 19:01 UTC, achou11 commented on src/renderer/src/components/Map.tsx
> +			style: 'https://demotiles.maplibre.org/style.json',
ideally the style that's used comes from `useMapStyleUrl()` in `@comapeo/core-react`. By default, that provides a Mapbox-based map as the default, which I _think_ should work with MapLibreGL but I'm not actually super sure.

2025-01-07 17:56 UTC, achou11 requested changes

2025-01-07 17:56 UTC, achou11 commented on package.json
let's pin these added deps to exact versions e.g. `npm i -D --save-exact @vis.gl/react-maplibre maplibre-gl`

2025-01-07 17:56 UTC, achou11 commented on patches/@comapeo+core+2.1.0+001+fix-smp-fallback-map-setup.patch.patch
revert the renaming of this file

2025-01-07 17:56 UTC, achou11 commented on src/renderer/src/components/Map.tsx
> +export function Map() {
are there any props that might be useful to have to start off with? maybe too early to tell for now 🤔

2025-01-07 17:56 UTC, achou11 commented on src/renderer/src/components/Map.tsx
> +		styleUrlQuery.data ?? 'https://demotiles.maplibre.org/style.json'
added an issue in core for this: https://github.com/digidem/comapeo-core/issues/982

2025-01-07 17:57 UTC, achou11 commented on src/renderer/src/components/Map.tsx
> +			mapStyle="https://demotiles.maplibre.org/style.json"
although I initially suggested using the hook here, it turns out that MapLibre dropped support for `mapbox://` urls, which our default online style currently contains. there's a way of fixing that by using https://github.com/rowanwins/maplibregl-mapbox-request-transformer but it requires the renderer needing access to the the access token, which isn't ideal and probably prone to breaking under other circumstances. Will file an issue to fix the mapbox-specific urls in core but for now, i think it's okay to use the MapLibre demotiles url for the `mapStyle`, like you were doing before.

added an issue in core for this: https://github.com/digidem/comapeo-core/issues/982

2025-01-07 18:24 UTC, cimigree commented on patches/@comapeo+core+2.1.0+001+fix-smp-fallback-map-setup.patch.patch
Oops

2025-01-07 18:31 UTC, cimigree commented on src/renderer/src/components/Map.tsx
> +export function Map() {
It might be too early to know as you say.
We can eventually add the onClick for handling observation clicks, or minZoom/maxZoom maybe? As far as I can tell, for right now we only need the basics so I didn't change anything.

2025-01-07 18:50 UTC, achou11 approved these changes

2025-01-07 19:31 UTC, achou11 commented on src/renderer/src/components/Map.tsx
> +import React from 'react'
this import isn't necessary

```suggestion
```

2025-01-07 20:11 UTC, merged