chore: handle invites to projects
digidem/comapeo-desktop pull request #70
Opened 2024-12-17 17:05 UTC by cimigree

closes #42 
Adds files to listen for invites, handle them when they come in, and accept or reject an invite to a project.
Used this notion doc: https://www.notion.so/digidem/Desktop-Invites-Architecture-15a1b08162d58053b27dd7b6133e7e33

I set up a test but am getting this error:
Error: Cannot find module '/Users/cindygreen/awana/comapeo-desktop/node_modules/@comapeo/core-react/dist/contexts/ClientApi' imported from /Users/cindygreen/awana/comapeo-desktop/node_modules/@comapeo/core-react/dist/index.js

I am not sure if it is a problem with my test or with core-react.
When I go in and add .js to the imports throughout the dist folder, it does run (although it currently fails). Just checking to see if that is a me problem or a comapeo-core problem.

2025-01-16 17:17 UTC, achou11 requested changes
Only an initial code review and didn't actually try out the feature (can I even do that?).

Upgrading to `@comapeo/core-react` to v2 will reduce the diff here a bit. I have a separate PR for that via #85 

Didn't take a good look at the test just yet but I think our testing setup needs to be improved in order to make it less tedious to write (Erik had started work on it but I think it's worth revisiting - I had lots of feedback on it and might just work on it myself)

2025-01-16 22:48 UTC, cimigree commented on src/renderer/src/hooks/usePendingInvites.ts
> +export function usePendingInvites() {
Ok I tried to do this and the dedupe...Will be curious if I did it as you imagined.

2025-01-16 22:49 UTC, cimigree commented on src/renderer/src/routes/Onboarding/JoinProjectScreen.$inviteId.tsx
Ok. UI is not awesome, but it is basic and is there. Will wait for a design...
<img width="1199" alt="Screenshot 2025-01-16 at 5 45 40 PM" src="https://github.com/user-attachments/assets/4d23f147-8c61-404e-a546-5b0b88cc92db" />

2025-01-16 22:49 UTC, cimigree commented on src/renderer/src/components/InviteListener.test.tsx
Yes please!

2025-01-16 22:49 UTC, cimigree commented on src/renderer/src/components/InviteListener.tsx
> +	}, [clientApi, location.pathname, navigate, rejectInvite])
Ok.

2025-01-16 22:49 UTC, cimigree commented on src/renderer/src/components/InviteListener.tsx
> +			}
Ok.

2025-01-16 22:52 UTC, cimigree commented
@achou11 I did as you requested, but I also added a Dev feature to be able to simulate an invite... Seen on every screen but it only works on the CreateJoin Project screen.
When you click it once, it takes you to the invite not found screen.
When you click it once you are on that screen, you can see the actual Join Project Screen.
The buttons to accept or decline do nothing except log the error.
I left the other logic there to be valid when a real invite is emitted and the other logic that works for dev simulation.
<img width="1197" alt="Screenshot 2025-01-16 at 5 45 51 PM" src="https://github.com/user-attachments/assets/b87f1ece-0808-49e2-ae1c-58bbb4535a65" />

2025-01-20 14:28 UTC, ErikSin commented
Hey, thanks for all the work on this. Gregor and I realized that there are some blockers with this architecture. If we delete CoMapeo on desktop, we don't actually delete the data. This would mean if the user tries to delete CoMapeo in order to get back to the "join a project screen", it would not work. Lets put a pause on this work as we will need to change the design to account for this. 

Thanks for doing the work and sorry that we caught this a little too late.

2025-07-07 21:39 UTC, achou11 commented
Closing this as it's been implemented via #124

2025-07-07 21:39 UTC, closed without merging